### ISSUE TITLE
Example has incorrect syntax for arduino 1.0.5-r2

### ISSUE THREAD

**Issue by mbainrot** [jmalloc/arduino-mcp4xxx#1]
On line 4 it has "use namespace icecave::arduino";

This throws an error, changing it to using resolves issue. 

Seems like just some teething problems for different versions of arduino ide

**Comment by jmalloc** [comment]
Fixed in https://github.com/jmalloc/arduino-mcp4xxx/commit/ad4a6e09a607c932e88d09890097d3ccd1696474
