### ISSUE TITLE
Arduino versions beyond 1.6.5 fail to compile namespaces

### ISSUE THREAD

**Issue by jdslabs** [jmalloc/arduino-mcp4xxx#3]
Just a heads up to anyone trying this example: namespaces do not compile in Arduino 1.6.6 and newer. Both 1.6.11 and 1.6.8 failed for me, while v1.6.5 compiles

This bug should be reopened:
https://github.com/arduino/arduino-builder/issues/44

It's worth adding a note to the readme until Arduino resolves.

**Comment by jmalloc** [comment]
Fixed in https://github.com/arduino/arduino-builder/commit/ec6c2c495c246be1b383b3d882a3d0fee89f0c7c
